all: test_message test_turning test_heading


test_message:
	PYTHONPATH=.:../src python test_message.py

test_turning:
	PYTHONPATH=.:../src python test_turning.py
test_heading:
	PYTHONPATH=.:../src python test_heading.py
